service: graphql-test

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-central-1

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get
